### ISSUE TITLE
No RAK file found

### ISSUE THREAD

**Issue by donat-m** [donat-m/Zuerich3D#12]
### No rak file found error in Travis-CI configuration
https://travis-ci.community/t/no-rakefile-found-when-adding-travis-to-a-github-project/3520

seems that the language is mandatory in travis

**Comment by donat-m** [comment]
![Travis-CI](https://user-images.githubusercontent.com/52152977/70384399-3987db80-197e-11ea-9c5f-be7785d6566b.png)

**Comment by donat-m** [comment]
fixed wi9th setting language to Objective-C

**Comment by donat-m** [comment]
now there is a problem with the public key. Error states bad **magic number**.
First had a key without passphrase what seem not to work in batch mode without prompt
Then I regenerated the key with passphrase and uploaded to GitHub and entered into the upload.enc file but still have the same issue :-(

**Comment by muimsd** [comment]
i can solve the issue.

**Comment by donat-m** [comment]
cool  go for it
but I solved it by setting the language to Objective-C
Now the issue is Bad Magic Number from using the upload.enc key file (Public-Key of my SSH Keypair uploaded to GitHub)

Mit Bestem Gruss

Donat Müller

MRS Mind Research Systems GmbH
Donat Müller
Schwingerstrasse 7
CH-8006 Zürich

+41 78 920 31 92
www.mrs.ch
zuerich3d.org@protonmail.com

https://zuerich3d.blogspot.com
https://www.zuerich3d.org
https://www.zuerich3d.com
https://4mrs.wordpress.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Montag, Dezember 16, 2019 6:17 PM schrieb Muhammad Imran Siddique <notifications@github.com>:

**Comment by muimsd** [comment]
I am waiting for Upwork contract.

**Comment by donat-m** [comment]
ok I'll fix it

Mit Bestem Gruss

Donat Müller

MRS Mind Research Systems GmbH
Donat Müller
Schwingerstrasse 7
CH-8006 Zürich

+41 78 920 31 92
www.mrs.ch
zuerich3d.org@protonmail.com

https://zuerich3d.blogspot.com
https://www.zuerich3d.org
https://www.zuerich3d.com
https://4mrs.wordpress.com

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Am Dienstag, Dezember 17, 2019 3:28 PM schrieb Muhammad Imran Siddique <notifications@github.com>:

**Comment by donat-m** [comment]
Fixed with settings Language: Objective-C
