### ISSUE TITLE
Create two Game Characters

### ISSUE THREAD

**Issue by donat-m** [donat-m/Zuerich3D#6]
One male one female character in the age of 25 to 30 years old.

- Estimated effort: 2.5 hrs
- Estimated deadline: December 3rd
- Assignee: @atepkinniku

**Comment by atepkinniku** [comment]
I already created this project https://we.tl/t-iKbttvujPI Let me know if you have some feed backs? Thank you

**Comment by donat-m** [comment]
Great Job Atep Thanks a lot
